version: '3.9'
services: 
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
    - .:/app
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    container_name: referals
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33060:3306
    extra_hosts:
      - host.docker.internal:host-gateway

volumes: 
  dbdata:
    